x-airflow-common: &airflow-common
  environment: &airflow-common-env
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${PG_DB}
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${PG_DB}
    AIRFLOW__CELERY__BROKER_URL: redis://:@${REDIS_HOST}:6379/0
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "${AIRFLOW_BASE_URL}/execution/"
  volumes:
    - ${AIRFLOW_PROJ_DIR}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR}/certs:/opt/airflow/certs:ro
  user: "${AIRFLOW_UID:-50000}:0"

services:
  airflow-worker:
    image: ${AIRFLOW_EXTENDED_IMAGE}
    hostname: ${AIRFLOW_WORKER_HOSTNAME}
    ports:
      - 8793:8793
    <<: *airflow-common
    command: celery worker
    healthcheck:
      # yamllint disable rule:line-length
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
    restart: always
